on:
  deployment_status

jobs:
  vercel-hook-test:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    name: Vercel hook test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: "actions/checkout@v3"
        with:
          ref: ${{ github.event.deployment_status.ref }}

      - name: "Github Script Action Test"
        id: gh-script-action-test
        uses: "actions/github-script@v7"
        with:
          script: |
            const fs = require("node:fs/promises");
            const { resolve } = require("node:path");
            const filePath = resolve("./legacy/package.json");
            const contentStr = await readFile(filePath, { encoding: "utf8" });
            const contentJson = JSON.parse(contentStr);
            console.log(JSON.stringify(context));
            return { version: contentJson.version };
